### PR TITLE
fix crash when api-problem tries to encode malformed UTF-8 to JSON

### LINKED ISSUE #40: ApiProblem crashes when trying to render malformed UTF-8 sequences
- [x] I was not able to find an [open](https://github.com/zendframework/zend-problem-details/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-problem-details/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Malformed UTF-8 sequences cause zend-problem-details to throw the following error:

```
TypeError: Argument 3 passed to Zend\ProblemDetails\ProblemDetailsResponseFactory::generateResponse() must be of the type string, boolean given, called in /code/src/ProblemDetailsResponseFactory.php on line 302

/code/src/ProblemDetailsResponseFactory.php:351
/code/src/ProblemDetailsResponseFactory.php:302
/code/src/ProblemDetailsResponseFactory.php:255
/code/src/ProblemDetailsResponseFactory.php:272
```

The issue is, that `json_encode()` will return an `false` when called without the option `JSON_PARTIAL_OUTPUT_ON_ERROR` but with malformed UTF-8 data to encode.

We found this error because someone randomly inserted characters in the base64 values of the HTTP Basic Authorization header which lead `base64_decode()` to return malformed UTF-8 which led to ProblemDetails crashing because the malformed UTF-8 sequence was in the stack trace of the error report.

### Code to reproduce the issue

See db3d795.

### Expected results

* ApiProblem should still be rendered
### Actual results

`TypeError` thrown.

### PR DESCRIPTION
**Pull request by BreiteSeite**
This fixes #40.

Instead of throwing a `TypeError`, the malformed UTF-8 is now omitted.

- [x] Are you fixing a bug?
  - [x] Detail how the bug is invoked currently.
  - [x] Detail the original, incorrect behavior.
  - [x] Detail the new, expected behavior.
  - [x] Base your feature on the `master` branch, and submit against that branch.
  - [x] Add a regression test that demonstrates the bug, and proves the fix.
  - [x] Add a `CHANGELOG.md` entry for the fix.

### CODE REVIEW

File: src/ProblemDetailsResponseFactory.php [hunk 1]
```diff
@@ -16,7 +16,6 @@
 use Psr\Http\Message\ServerRequestInterface;
 use Spatie\ArrayToXml\ArrayToXml;
 use Throwable;
-
```
Comment (weierophinney) [inline src/ProblemDetailsResponseFactory.php]: We use an empty line between class imports and function imports, and again between function and constant imports. Please re-instate those breaks.

File: src/ProblemDetailsResponseFactory.php [hunk 2]
```diff
@@ -30,11 +29,11 @@
 use function print_r;
 use function sprintf;
 use function strpos;
-
 use const JSON_PRESERVE_ZERO_FRACTION;
 use const JSON_PRETTY_PRINT;
 use const JSON_UNESCAPED_SLASHES;
 use const JSON_UNESCAPED_UNICODE;
+use const JSON_PARTIAL_OUTPUT_ON_ERROR;
```
Comment (weierophinney) [inline src/ProblemDetailsResponseFactory.php]: We alphabetize imports of the same type; this entry belongs at the top of the list. :)

File: src/ProblemDetailsResponseFactory.php [hunk 3]
```diff
@@ -213,7 +215,8 @@ public function __construct(
         };
         $this->isDebug = $isDebug;
         if (! $jsonFlags) {
-            $jsonFlags = JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRESERVE_ZERO_FRACTION;
+            $jsonFlags = JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRESERVE_ZERO_FRACTION
+                | JSON_PARTIAL_OUTPUT_ON_ERROR;
```
Comment (weierophinney) [inline src/ProblemDetailsResponseFactory.php]: If you're going to break this onto another line, do a line per `|`, please.

File: test/ProblemDetailsResponseFactoryFactoryTest.php [hunk 4]
```diff
@@ -82,7 +82,8 @@ public function testLackOfConfigServiceResultsInFactoryUsingDefaults() : void
         $this->assertInstanceOf(ProblemDetailsResponseFactory::class, $factory);
         $this->assertAttributeSame(ProblemDetailsResponseFactory::EXCLUDE_THROWABLE_DETAILS, 'isDebug', $factory);
         $this->assertAttributeSame(
-            JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRESERVE_ZERO_FRACTION,
+            JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRESERVE_ZERO_FRACTION
+            | JSON_PARTIAL_OUTPUT_ON_ERROR,
```
Comment (weierophinney) [inline test/ProblemDetailsResponseFactoryFactoryTest.php]: Same comment here and elsewhere; one `|`/constant pair per line, please.

File: test/ProblemDetailsResponseFactoryFactoryTest.php [hunk 5]
```diff
@@ -103,11 +104,7 @@ public function testUsesPrettyPrintFlagOnEnabledDebugMode() : void
         $factoryFactory = new ProblemDetailsResponseFactoryFactory();
         $factory = $factoryFactory($this->container->reveal());
 
-        $this->assertAttributeSame(
-            JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRESERVE_ZERO_FRACTION,
-            'jsonFlags',
-            $factory
-        );
+        $this->assertSame(JSON_PRETTY_PRINT, Assert::readAttribute($factory, 'jsonFlags') & JSON_PRETTY_PRINT);
```
Comment (weierophinney) [inline test/ProblemDetailsResponseFactoryFactoryTest.php:109]: I always forget my bitwise operators - thanks for simplifying this!

File: test/ProblemDetailsResponseFactoryTest.php [hunk 6]
```diff
@@ -432,4 +434,41 @@ function () {
...
+    public function testRenderWithMalformedUtf8Sequences(): void
+    {
+        $e = $this->prophesize(RuntimeException::class)->willImplement(ProblemDetailsExceptionInterface::class);
+        $e->getStatus()->willReturn(400);
+        $e->getDetail()->willReturn('Exception details');
+        $e->getTitle()->willReturn('Invalid client request');
+        $e->getType()->willReturn('https://example.com/api/doc/invalid-client-request');
+        $e->getAdditionalData()->willReturn([
+            'malformed-utf8' => self::UTF_8_INVALID_2_OCTET_SEQUENCE,
+            ]);
```
Comment (weierophinney) [inline test/ProblemDetailsResponseFactoryTest.php]: This line should have one level less indentation (should line up with the line where the array was opened).

**Review by weierophinney — CHANGES_REQUESTED** [review]
Looks good - I only have a few minor formatting/CS changes for you!

File: src/ProblemDetailsResponseFactory.php (hunk 1 above)
Comment (BreiteSeite) [reply src/ProblemDetailsResponseFactory.php]: Sorry, PHPStorm autoformat. :) Reverted the formatting.

File: src/ProblemDetailsResponseFactory.php (hunk 2 above)
Comment (BreiteSeite) [reply src/ProblemDetailsResponseFactory.php]: Moved it to the top.

File: src/ProblemDetailsResponseFactory.php (hunk 3 above)
Comment (BreiteSeite) [reply src/ProblemDetailsResponseFactory.php]: Done

File: test/ProblemDetailsResponseFactoryFactoryTest.php (hunk 5 above)
Comment (BreiteSeite) [reply test/ProblemDetailsResponseFactoryFactoryTest.php:109]: No worries. The test failed me when it really shouldn't so i thought it was a bit over-assertive. :)

File: test/ProblemDetailsResponseFactoryTest.php (hunk 6 above)
Comment (BreiteSeite) [reply test/ProblemDetailsResponseFactoryTest.php]: No clue how that slipped phpcs and my eyes. Fixed.

**Comment by weierophinney** [comment]
Thanks, @BreiteSeite!
